DROP TABLE  "SECURITY_MODULE";
CREATE TABLE  "SECURITY_MODULE" (
"ID" NUMBER(20) NOT NULL ,
"DESCRIPTION" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"NAME" VARCHAR2(32 BYTE) NOT NULL ,
"PRIORITY" NUMBER(11) DEFAULT NULL  NULL ,
"URL" VARCHAR2(255 BYTE) NOT NULL ,
"PARENT_ID" NUMBER(20) DEFAULT NULL  NULL ,
"SN" VARCHAR2(32 BYTE) NULL ,
"TYPE" VARCHAR2(32 BYTE) DEFAULT 'security'  NOT NULL ,
"ENABLE" NUMBER(2) DEFAULT '1'  NULL ,

"CREATER" NUMBER(20)  NULL ,
"CREATETIME" VARCHAR2(20)  NULL ,
"MODIFYER" NUMBER(20)  NULL ,
"MODIFYTIME" VARCHAR2(20)  NULL 

)
LOGGING
NOCOMPRESS
NOCACHE;

ALTER TABLE  "SECURITY_MODULE" ADD PRIMARY KEY ("ID");

COMMENT ON COLUMN  "SECURITY_MODULE"."TYPE" IS '模块类型';
COMMENT ON COLUMN  "SECURITY_MODULE"."ENABLE" IS '是否启用（1：启用，0：停用）';

DROP SEQUENCE  "SEQ_SECURITY_MODULE";
CREATE SEQUENCE  "SEQ_SECURITY_MODULE"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 30
 NOCACHE ;


INSERT INTO "SECURITY_MODULE" VALUES ('1', '所有模块的根节点，不能删除', '业务模块', '1', '#', null, '', '0', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('2', '安全管理:包含权限管理、模块管理', '安全管理', '1', '#', '1', 'Security', '1', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('3', '用户管理', '用户管理', '1', '/security/user/list', '2', 'User', '1', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('4', '角色管理', '角色管理', '2', '/security/role/list', '2', 'Role', '1', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('5', '模块管理', '模块管理', '4', '/security/module/tree', '2', 'Module', '1', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('6', '缓存管理', '缓存管理', '5', '/security/cacheManage/index', '2', 'CacheManage', '1', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('25', '组织管理', '组织管理', '4', '/security/organization/tree', '2', 'Organization', '1', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('7', '用户管理新增操作', '新增', '1', '#', '3', 'save', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('8', '用户管理删除操作', '删除', '3', '#', '3', 'delete', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('9', '用户管理修改操作', '修改', '2', '#', '3', 'edit', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('10', '用户管理查询操作', '查看', '0', '#', '3', 'view', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('11', '角色管理新增操作', '新增', '1', '#', '4', 'save', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('12', '角色管理删除操作', '删除', '3', '#', '4', 'delete', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('13', '角色管理修改操作', '修改', '2', '#', '4', 'edit', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('14', '角色管理查询操作', '查看', '0', '#', '4', 'view', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('15', '缓存管理新增操作', '新增', '1', '#', '6', 'save', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('16', '缓存管理删除操作', '删除', '3', '#', '6', 'delete', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('17', '缓存管理修改操作', '修改', '2', '#', '6', 'edit', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('18', '缓存管理查询操作', '查看', '0', '#', '6', 'view', '2', '1',sysdate,'1',sysdate);
--INSERT INTO "SECURITY_MODULE" VALUES ('19', '模块管理新增操作', '新增模块', '1', '#', '5', 'save', '2', '1',sysdate,'1',sysdate);
--INSERT INTO "SECURITY_MODULE" VALUES ('20', '模块管理删除操作', '删除', '4', '#', '5', 'delete', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('21', '模块管理修改操作', '修改', '3', '#', '5', 'edit', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('22', '模块管理查询操作', '查看', '0', '#', '5', 'view', '2', '1',sysdate,'1',sysdate);
--INSERT INTO "SECURITY_MODULE" VALUES ('23', '模块管理新增业务操作', '新增操作', '2', '#', '5', 'saveoperation', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('24', '用户管理查询操作', '查看', '0', '#', '2', 'view', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('26', '查看操作', '查看', '1', '#', '25', 'view', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('27', '组织管理新增操作', '新增', '1', '#', '25', 'save', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('28', '组织管理删除操作', '删除', '3', '#', '25', 'delete', '2', '1',sysdate,'1',sysdate);
INSERT INTO "SECURITY_MODULE" VALUES ('29', '组织管理修改操作', '修改', '2', '#', '25', 'edit', '2', '1',sysdate,'1',sysdate);





DROP TABLE  "SECURITY_ORGANIZATION";
CREATE TABLE  "SECURITY_ORGANIZATION" (
"ID" NUMBER(20) NOT NULL ,
"DESCRIPTION" VARCHAR2(255 BYTE) DEFAULT NULL  NULL ,
"NAME" VARCHAR2(64 BYTE) NOT NULL ,
"CODE" VARCHAR2(64 BYTE) NOT NULL ,
"PARENT_ID" NUMBER(20) DEFAULT NULL  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE  "SECURITY_ORGANIZATION" ADD PRIMARY KEY ("ID");

INSERT INTO  "SECURITY_ORGANIZATION" VALUES ('1', '不能删除。', '根组织','ROOT', null);

DROP SEQUENCE   SEQ_SECURITY_ORGANIZATION ;
CREATE SEQUENCE   SEQ_SECURITY_ORGANIZATION 
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 2
 NOCACHE ;

DROP TABLE  "SECURITY_ROLE";
CREATE TABLE  "SECURITY_ROLE" (
"ID" NUMBER(20) NOT NULL ,
"NAME" VARCHAR2(32 BYTE) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE;

ALTER TABLE  "SECURITY_ROLE" ADD PRIMARY KEY ("ID");

INSERT INTO  "SECURITY_ROLE" VALUES ('1', '超级管理员');

DROP SEQUENCE   SEQ_SECURITY_ROLE ;
CREATE SEQUENCE   SEQ_SECURITY_ROLE 
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 2
 NOCACHE ;


DROP TABLE  "SECURITY_ROLE_PERMISSION";
CREATE TABLE  "SECURITY_ROLE_PERMISSION" (
"ID" NUMBER(20) NOT NULL ,
"ROLE_ID" NUMBER(20) NOT NULL ,
"PERMISSION" VARCHAR2(255 BYTE) DEFAULT NULL  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE  "SECURITY_ROLE_PERMISSION" ADD PRIMARY KEY ("ID");

DROP SEQUENCE  "SEQ_SECURITY_ROLE_PERMISSION";
CREATE SEQUENCE  "SEQ_SECURITY_ROLE_PERMISSION"
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 1
 NOCACHE ;

INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Security:view');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'User:view');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'User:save');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'User:edit');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'User:delete');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Role:view');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Role:save');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Role:edit');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Role:delete');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Module:view');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Module:save');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Module:saveoperation');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Module:edit');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Module:delete');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Organization:view');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Organization:save');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Organization:edit');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'Organization:delete');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'CacheManage:view');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'CacheManage:save');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'CacheManage:edit');
INSERT INTO  "SECURITY_ROLE_PERMISSION" VALUES (SEQ_SECURITY_ROLE_PERMISSION.nextval, '1', 'CacheManage:delete');


DROP TABLE  "SECURITY_USER";
CREATE TABLE  "SECURITY_USER" (
"ID" NUMBER(20) NOT NULL ,
"CREATE_TIME" DATE DEFAULT NULL  NULL ,
"PASSWORD" VARCHAR2(64 BYTE) NOT NULL ,
"SALT" VARCHAR2(32 BYTE) NOT NULL ,
"STATUS" VARCHAR2(20 BYTE) NOT NULL ,
"USERNAME" VARCHAR2(32 BYTE) NOT NULL ,
"EMAIL" VARCHAR2(128 BYTE) NULL ,
"REALNAME" VARCHAR2(32 BYTE) NOT NULL ,
"PHONE" VARCHAR2(32 BYTE) DEFAULT NULL  NULL ,
"ORG_ID" NUMBER(20) DEFAULT NULL  NULL ,
"USERTYPE" NUMBER(2) NOT NULL 
)
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE  "SECURITY_USER" ADD PRIMARY KEY ("ID");

COMMENT ON COLUMN  "SECURITY_USER"."USERTYPE" IS '用户类型';

INSERT INTO  "SECURITY_USER" VALUES ('2', TO_DATE('2012-08-03 14:58:38', 'YYYY-MM-DD HH24:MI:SS'), '334e65571ac44a565a74d11a43e0f853e091dfe6', '7fc59f59e241db8d', 'enabled', 'system', '', '系统后台/未知用户', '', '1', '1');
INSERT INTO  "SECURITY_USER" VALUES ('1', TO_DATE('2012-08-03 14:58:38', 'YYYY-MM-DD HH24:MI:SS'), '334e65571ac44a565a74d11a43e0f853e091dfe6', '7fc59f59e241db8d', 'enabled', 'admin', '', '系统管理员', '', '1', '1');

DROP SEQUENCE   SEQ_SECURITY_USER ;
CREATE SEQUENCE   SEQ_SECURITY_USER 
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 3
 NOCACHE ;

DROP TABLE  "SECURITY_USER_ROLE";
CREATE TABLE  "SECURITY_USER_ROLE" (
"ID" NUMBER(20) NOT NULL ,
"PRIORITY" NUMBER(11) NOT NULL ,
"ROLE_ID" NUMBER(20) DEFAULT NULL  NULL ,
"USER_ID" NUMBER(20) DEFAULT NULL  NULL 
)
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE  "SECURITY_USER_ROLE" ADD PRIMARY KEY ("ID");

INSERT INTO  "SECURITY_USER_ROLE" VALUES ('1', '1', '1', '1');

DROP SEQUENCE   SEQ_SECURITY_USER_ROLE ;
CREATE SEQUENCE   SEQ_SECURITY_USER_ROLE 
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9999999999999999999999999999
 START WITH 2
 NOCACHE ;


#创建主键SEQUENCE
DROP SEQUENCE SEQ_BASE_DOC;
CREATE SEQUENCE SEQ_BASE_DOC
 INCREMENT BY 1
 START WITH 1
 NOMAXvalue
 NOCYCLE
 NOCACHE;

#创建数据库表
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE　BASE_DOC';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
CREATE TABLE BASE_DOC (
    ID DECIMAL(19)  NOT NULL ,
    NAME NVARCHAR2(64)  NOT NULL ,
    SUFFIX NVARCHAR2(16)  NOT NULL ,
    PATH NVARCHAR2(64) ,
    MD5 NVARCHAR2(32) ,
    EXPIRATION NCHAR(19) ,
    CACHE_KEY NVARCHAR2(40) ,
    CREATER DECIMAL(19) ,
    MODIFYER DECIMAL(19) ,
    CREATETIME NCHAR(19) ,
    MODIFYTIME NCHAR(19) ,
    CONSTRAINT BASE_BASE_DOC_PRIMARY PRIMARY KEY(ID)

);

comment on table BASE_DOC is '上传组件';
comment on column BASE_DOC.ID is '主键';
comment on column BASE_DOC.NAME is '文件名称';
comment on column BASE_DOC.SUFFIX is '文件类型';
comment on column BASE_DOC.PATH is '存储路径（相对）';
comment on column BASE_DOC.MD5 is 'MD5码';
comment on column BASE_DOC.EXPIRATION is '(缓存文件)过期时间';
comment on column BASE_DOC.CACHE_KEY is '(缓存文件)key值';
comment on column BASE_DOC.CREATER is '创建人';
comment on column BASE_DOC.MODIFYER is '最后修改人';
comment on column BASE_DOC.CREATETIME is '创建时间';
comment on column BASE_DOC.MODIFYTIME is '最后修改时间';


#创建主键SEQUENCE
DROP SEQUENCE SEQ_BASE_DOC_REL;
CREATE SEQUENCE SEQ_BASE_DOC_REL
 INCREMENT BY 1
 START WITH 1
 NOMAXvalue
 NOCYCLE
 NOCACHE;

#创建数据库表
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE　BASE_DOC_REL';
  EXCEPTION WHEN OTHERS THEN NULL;
END;
CREATE TABLE BASE_DOC_REL (
    ID DECIMAL(19)  NOT NULL ,
    CACHE_KEY NVARCHAR2(64) ,
    CREATER DECIMAL(19) ,
    MODIFYER DECIMAL(19) ,
    CREATETIME NCHAR(19) ,
    MODIFYTIME NCHAR(19) ,
    CONSTRAINT BASE_DOC_REL_PRIMARY PRIMARY KEY(ID)

);

comment on table BASE_DOC_REL is '上传组件';
comment on column BASE_DOC_REL.ID is '主键';
comment on column BASE_DOC_REL.CACHE_KEY is '(缓存文件)key值';
comment on column BASE_DOC_REL.CREATER is '创建人';
comment on column BASE_DOC_REL.MODIFYER is '最后修改人';
comment on column BASE_DOC_REL.CREATETIME is '创建时间';
comment on column BASE_DOC_REL.MODIFYTIME is '最后修改时间';





 